name: Terraform GCP Deploy

on:
  workflow_dispatch:
    inputs:
      project_id:
        description: "GCP Project ID"
        required: true
        default: 'project-id-1234'
      vpc_name:
        description: "VPC Name"
        required: true
        default: 'my-vpc'
      subnet_name:
        description: "Subnet Name"
        required: true
        default: 'my-subnet'
      instance_name:
        description: "Compute Engine Name"
        required: true
        default: 'my-instance'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: |
          terraform plan \
            -var="project_id=${{ github.event.inputs.project_id }}" \
            -var="vpc_name=${{ github.event.inputs.vpc_name }}" \
            -var="subnet_name=${{ github.event.inputs.subnet_name }}" \
            -var="instance_name=${{ github.event.inputs.instance_name }}"

      - name: Terraform Apply
        run: |
          terraform apply -auto-approve \
            -var="project_id=${{ github.event.inputs.project_id }}" \
            -var="vpc_name=${{ github.event.inputs.vpc_name }}" \
            -var="subnet_name=${{ github.event.inputs.subnet_name }}" \
            -var="instance_name=${{ github.event.inputs.instance_name }}"
